spring.application.name=admin-server
server.port=9090  
spring.boot.admin.ui.public-url=https://newcodes.net/admin/monitor/

spring.security.user.name=${ADMIN_NAME}
spring.security.user.password=${ADMIN_PASSWORD}
spring.security.user.roles=${ROLES}