services:
  postgres:
    image: paradedb/paradedb:latest
    environment:
      POSTGRES_USER: newcodes
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: small_town
    volumes:
      - ./postgres_backup_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U newcodes -d small_town"]
      timeout: 5s
      retries: 5
      start_period: 30s # PostgreSQL이 시작될 때까지 기다리는 시간

volumes:
  postgres_data: