worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 768;
}

http {
    resolver 127.0.0.11 valid=30s ipv6=off;  # Docker 내장 DNS, 컨테이너 재시작 시 IP 변경 반영
    resolver_timeout 10s;

    ##
    # Basic Settings
    ##
    sendfile on;
    tcp_nopush on;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ##
    # SSL Settings
    ##
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    ##
    # Logging Settings
    ##
    access_log /var/log/nginx/access.log;

    ##
    # Gzip Settings
    ##
    gzip on;
    gzip_vary on;
    gzip_min_length 256;
    gzip_types
        application/json
        text/plain
        text/css
        application/javascript
        application/xml;

    ##
    # Virtual Host Configs
    ##
    include /etc/nginx/conf.d/*.conf;  # ✅ 도커에서는 이 경로로 설정들을 불러옴
}
